apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: app
          image: tuanhung/eureka-service:1.0.0
          ports:
            - containerPort: 8761
          imagePullPolicy: Always
          env:
          - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
            value: http://naming-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - port: 8761
      targetPort: 8761
  type: LoadBalancer
