apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: app
          image: tuanhung/gateway-service:1.0.0
          env:
            - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
              value: http://eureka-service:8761/eureka
            - name: SPRING.ZIPKIN.BASEURL
              value: http://zipkin:9411/
          ports:
            - containerPort: 8765
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8765
      targetPort: 8765
  type: LoadBalancer

