pipeline {
    agent any

    triggers {
        pollSCM '* * * * *'
    }

    tools {
        maven 'M3'
    }
    stages {
        stage('Build') {
            dir('auth-service') {
                steps {
                    sh 'mvn -DskipTests=true clean package'
                }
            }
        }

        stage('Build docker image') {
            dir('auth-service') {
                steps {
                    sh 'docker build -t tuanhung/auth-service:1.0.0 .'
                }
            }
        }

        stage('Push image to Docker Hub') {
            environment {
                DOCKER_HUB_LOGIN = credentials('docker-hub')
            }
            dir('auth-service') {
               steps {
                   sh 'docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW'
                   sh 'docker image push tuanhung/auth-service:1.0.0'
               }
            }
        }
    }
}