pipeline {
    agent any

    triggers {
        pollSCM '* * * * *'
    }

    tools {
        maven 'M3'
    }
    stages {
        stage('Build') {
            steps {
                dir('auth-service') {
                    sh 'mvn -DskipTests=true clean package'
                }
            }
        }

        stage('Build docker image') {
            steps {
                dir('auth-service') {
                    sh 'docker build -t tuanhung/auth-service:1.0.0 .'
                }
            }
        }

        stage('Push image to Docker Hub') {
            environment {
                DOCKER_HUB_LOGIN = credentials('docker-hub')
            }
            steps {
                dir('auth-service') {
                    sh 'docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW'
                    sh 'docker image push tuanhung/auth-service:1.0.0'
                }

            }
        }

        stage('Deploying App to Kubernetes') {
          steps {
            dir('kube') {
                sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'
                sh 'chmod u+x ./kubectl'
                sh 'kubectl apply -f auth-service.yaml'
            }
          }
        }
    }
}